In [40]:
from datetime import timedelta, datetime

import pandas as pd

In [3]:
medicine = pd.read_csv('../../excercises/week2/Medical_Tracker.csv')
medicine

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,name,ingredient,category,symptoms,instructions,dosage,frequency_hours,safety,urgency
0,0.0,0.0,0.0,1,Panadol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Swallow tablets with water. Can be taken with ...,500 mg to 1000 mg,4,Do not combine with other products containing ...,Low
1,1.0,1.0,1.0,2,Advil,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, swelling, menstrual cramps...",Take with food or milk if it causes stomach ir...,200 mg to 400 mg,6,Avoid or seek medical advice if you have stoma...,Medium
2,2.0,2.0,2.0,3,Anadin,Aspirin,Over-the-Counter (OTC),Mild pain and fever,Swallow tablets as directed. Enteric-coated ta...,325 mg to 650 mg,4,Aspirin can increase bleeding risk and should ...,Medium
3,3.0,3.0,3.0,4,Amoxil,Amoxicillin,Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,250 mg to 500 mg,8,Do not take if you have a known serious penici...,High
4,4.0,4.0,4.0,5,Calpol,Paracetamol,Over-the-Counter (OTC),Pain and fever,Follow the product instructions and use the ap...,500 mg to 1000 mg,4,Do not combine with other paracetamol-containi...,Low
5,5.0,5.0,5.0,6,Nurofen,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and fever",Take with water. Food may help reduce stomach ...,200 mg to 400 mg,6,"NSAID precautions apply, particularly with sto...",Medium
6,6.0,6.0,6.0,7,Tylenol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Take with water and follow the product instruc...,500 mg to 1000 mg,6,Do not combine with other products containing ...,Low
7,7.0,7.0,7.0,8,Panadol Extra,"Paracetamol, Caffeine",Over-the-Counter (OTC),"Headache, pain, and fever",Swallow tablets with water and follow the prod...,500 mg Paracetamol + 65 mg Caffeine,4,Avoid combining with other paracetamol-contain...,Medium
8,8.0,8.0,8.0,9,Clarityn,Loratadine,Over-the-Counter (OTC),"Hay fever, sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,Seek medical advice if allergy symptoms are se...,Low
9,9.0,9.0,9.0,10,Loratadine,Loratadine,Over-the-Counter (OTC),Allergy symptoms such as sneezing and itchy eyes,Take once daily as directed.,10 mg,24,Do not exceed the recommended dose.,Low
10,10.0,10.0,10.0,11,Zyrtec,Cetirizine,Over-the-Counter (OTC),"Sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,May cause drowsiness in some people.,Low
11,11.0,11.0,11.0,12,Cetirizine,Cetirizine,Over-the-Counter (OTC),Allergy symptoms and hay fever,Take according to the product instructions.,10 mg,24,May cause drowsiness. Avoid driving if affected.,Low
12,12.0,12.0,12.0,13,Gaviscon,"Sodium alginate, Calcium carbonate",Over-the-Counter (OTC),"Heartburn, acid reflux, and indigestion","Take according to the product instructions, co...",Product-dependent,8,Seek medical advice for persistent or severe r...,Low
13,13.0,13.0,13.0,14,Nexium,Esomeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
14,14.0,14.0,14.0,15,Losec,Omeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
15,15.0,15.0,15.0,16,Imodium,Loperamide,Over-the-Counter (OTC),Short-term relief of uncomplicated diarrhea,Follow package directions and maintain adequat...,Product-dependent,6,Do not use for bloody diarrhea or high fever w...,Medium
16,16.0,16.0,16.0,17,Buscopan,Hyoscine butylbromide,Over-the-Counter (OTC),Abdominal cramps and spasms,Take as directed for abdominal cramps.,10 mg to 20 mg,6,Seek medical advice for severe or unexplained ...,Medium
17,17.0,17.0,17.0,18,Sudafed,Pseudoephedrine,Over-the-Counter (OTC),Nasal congestion from colds or allergies,Follow package directions and do not exceed th...,Product-dependent,6,May raise blood pressure or cause palpitations...,Medium
18,18.0,18.0,18.0,19,Benadryl,Diphenhydramine,Over-the-Counter (OTC),Allergy symptoms and some cold symptoms,Follow package instructions. May cause drowsin...,Product-dependent,6,May cause significant drowsiness. Avoid combin...,Medium
19,19.0,19.0,19.0,20,Strepsils,Amylmetacresol,Over-the-Counter (OTC),Sore throat and minor mouth irritation,Allow the lozenge to dissolve slowly in the mo...,Product-dependent,3,Do not exceed the recommended amount.,Low
20,20.0,20.0,20.0,21,Canesten,Clotrimazole,Over-the-Counter (OTC),Fungal skin infections such as athlete’s foot,Apply to the affected area as directed and kee...,Product-dependent,12,For external use only. Stop if severe irritati...,Low
21,21.0,21.0,21.0,22,Dulcolax,Bisacodyl,Over-the-Counter (OTC),Occasional constipation,Take with water and follow package instructions.,5 mg to 10 mg,24,Overuse can cause abdominal cramps and electro...,Medium
22,22.0,22.0,22.0,23,Senokot,Senna,Supplement,Occasional constipation,Take according to package instructions and mai...,7.5 mg to 15 mg,24,Long-term or excessive use may cause bowel or ...,Medium
23,23.0,23.0,23.0,24,Telfast,Fexofenadine,Over-the-Counter (OTC),Hay fever and hives,Take according to the product instructions.,120 mg to 180 mg,24,Follow age restrictions and product instructions.,Low
24,24.0,24.0,24.0,25,Aerius,Desloratadine,Over-the-Counter (OTC),Hay fever and hives,Take once daily as directed.,5 mg,24,Seek medical advice if symptoms persist despit...,Low
25,25.0,25.0,25.0,26,Augmentin,"Amoxicillin, Clavulanic acid",Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Do not take if you have a serious penicillin a...,High
26,26.0,26.0,26.0,27,Cipro,Ciprofloxacin,Prescription,Certain bacterial infections,Take exactly as prescribed.,Product-dependent,12,Prescription medicine with important drug inte...,High
27,27.0,27.0,27.0,28,Flagyl,Metronidazole,Prescription,Certain bacterial and parasitic infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Prescription medicine. Follow medical advice r...,High
28,28.0,28.0,28.0,29,Vicks,"Menthol, Camphor",First Aid,Minor cold symptoms and nasal congestion,Use according to the specific product instruct...,Product-dependent,6,Do not ingest products intended only for exter...,Low
29,29.0,0.0,NaN,30,Voltaren,Diclofenac,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,25–50 mg,8,"Avoid if you have stomach ulcers, kidney probl...",Medium
30,0.0,NaN,NaN,31,Motrin,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,200–400 mg,6,Avoid combining with other NSAIDs,Medium
31,NaN,NaN,NaN,32,Claritin,Loratadine,Over-the-Counter (OTC),"Sneezing, runny nose, itchy eyes, and allergies",Take once daily with or without food,10mg,24,Do not exceed the recommended dose,Low

In [106]:
medicine.loc[29]

Unnamed: 0.1                                                       0
Unnamed: 0                                                       NaN
id                                                                30
name                                                        Voltaren
ingredient                                                Diclofenac
category                                      Over-the-Counter (OTC)
symptoms                            Pain, inflammation, and swelling
instructions       Take with food or milk to reduce stomach irrit...
dosage                                                      25–50 mg
frequency_hours                                                    8
safety             Avoid if you have stomach ulcers, kidney probl...
urgency                                                       Medium
Name: 29, dtype: object

### Adding new details

In [107]:
id = len(medicine) +1
name = input("Enter medicine's name : ")
ing = input("Whats the ingredient : ")
cata = input("Whats the category : ")
sym = input("whats the symptoms : ")
inst = input("whats the instructions : ")
dos = input("whats the dosage : ")
frq = input("whats the frequency hours: ")
saf = input("whats the saftey precautions :")
urg = input("whats the urgency : ")

In [108]:
print(id)
print(name)
print(ing)
print(cata)
print(sym)
print(inst)
print(dos)
print(frq)
print(saf)
print(urg)

31
Motrin
Ibuprofen
Over-the-Counter (OTC)
Pain, inflammation, and swelling
Take with food or milk to reduce stomach irritation
200–400 mg
6
Avoid combining with other NSAIDs
Medium

In [109]:
updated_data = [{"id": id, "name": name, "ingredient":ing, "category":cata, "symptoms": sym,
"instructions":inst, "dosage": dos, "frequency_hours":frq, "safety" :saf, "urgency": urg,
}]

In [110]:
df = pd.DataFrame(updated_data)

In [111]:
medicine = pd.concat([medicine, df])

In [112]:
medicine

,Unnamed: 0.1,Unnamed: 0,id,name,ingredient,category,symptoms,instructions,dosage,frequency_hours,safety,urgency
0,0.0,0.0,1,Panadol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Swallow tablets with water. Can be taken with ...,500 mg to 1000 mg,4,Do not combine with other products containing ...,Low
1,1.0,1.0,2,Advil,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, swelling, menstrual cramps...",Take with food or milk if it causes stomach ir...,200 mg to 400 mg,6,Avoid or seek medical advice if you have stoma...,Medium
2,2.0,2.0,3,Anadin,Aspirin,Over-the-Counter (OTC),Mild pain and fever,Swallow tablets as directed. Enteric-coated ta...,325 mg to 650 mg,4,Aspirin can increase bleeding risk and should ...,Medium
3,3.0,3.0,4,Amoxil,Amoxicillin,Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,250 mg to 500 mg,8,Do not take if you have a known serious penici...,High
4,4.0,4.0,5,Calpol,Paracetamol,Over-the-Counter (OTC),Pain and fever,Follow the product instructions and use the ap...,500 mg to 1000 mg,4,Do not combine with other paracetamol-containi...,Low
5,5.0,5.0,6,Nurofen,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and fever",Take with water. Food may help reduce stomach ...,200 mg to 400 mg,6,"NSAID precautions apply, particularly with sto...",Medium
6,6.0,6.0,7,Tylenol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Take with water and follow the product instruc...,500 mg to 1000 mg,6,Do not combine with other products containing ...,Low
7,7.0,7.0,8,Panadol Extra,"Paracetamol, Caffeine",Over-the-Counter (OTC),"Headache, pain, and fever",Swallow tablets with water and follow the prod...,500 mg Paracetamol + 65 mg Caffeine,4,Avoid combining with other paracetamol-contain...,Medium
8,8.0,8.0,9,Clarityn,Loratadine,Over-the-Counter (OTC),"Hay fever, sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,Seek medical advice if allergy symptoms are se...,Low
9,9.0,9.0,10,Loratadine,Loratadine,Over-the-Counter (OTC),Allergy symptoms such as sneezing and itchy eyes,Take once daily as directed.,10 mg,24,Do not exceed the recommended dose.,Low
10,10.0,10.0,11,Zyrtec,Cetirizine,Over-the-Counter (OTC),"Sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,May cause drowsiness in some people.,Low
11,11.0,11.0,12,Cetirizine,Cetirizine,Over-the-Counter (OTC),Allergy symptoms and hay fever,Take according to the product instructions.,10 mg,24,May cause drowsiness. Avoid driving if affected.,Low
12,12.0,12.0,13,Gaviscon,"Sodium alginate, Calcium carbonate",Over-the-Counter (OTC),"Heartburn, acid reflux, and indigestion","Take according to the product instructions, co...",Product-dependent,8,Seek medical advice for persistent or severe r...,Low
13,13.0,13.0,14,Nexium,Esomeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
14,14.0,14.0,15,Losec,Omeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
15,15.0,15.0,16,Imodium,Loperamide,Over-the-Counter (OTC),Short-term relief of uncomplicated diarrhea,Follow package directions and maintain adequat...,Product-dependent,6,Do not use for bloody diarrhea or high fever w...,Medium
16,16.0,16.0,17,Buscopan,Hyoscine butylbromide,Over-the-Counter (OTC),Abdominal cramps and spasms,Take as directed for abdominal cramps.,10 mg to 20 mg,6,Seek medical advice for severe or unexplained ...,Medium
17,17.0,17.0,18,Sudafed,Pseudoephedrine,Over-the-Counter (OTC),Nasal congestion from colds or allergies,Follow package directions and do not exceed th...,Product-dependent,6,May raise blood pressure or cause palpitations...,Medium
18,18.0,18.0,19,Benadryl,Diphenhydramine,Over-the-Counter (OTC),Allergy symptoms and some cold symptoms,Follow package instructions. May cause drowsin...,Product-dependent,6,May cause significant drowsiness. Avoid combin...,Medium
19,19.0,19.0,20,Strepsils,Amylmetacresol,Over-the-Counter (OTC),Sore throat and minor mouth irritation,Allow the lozenge to dissolve slowly in the mo...,Product-dependent,3,Do not exceed the recommended amount.,Low
20,20.0,20.0,21,Canesten,Clotrimazole,Over-the-Counter (OTC),Fungal skin infections such as athlete’s foot,Apply to the affected area as directed and kee...,Product-dependent,12,For external use only. Stop if severe irritati...,Low
21,21.0,21.0,22,Dulcolax,Bisacodyl,Over-the-Counter (OTC),Occasional constipation,Take with water and follow package instructions.,5 mg to 10 mg,24,Overuse can cause abdominal cramps and electro...,Medium
22,22.0,22.0,23,Senokot,Senna,Supplement,Occasional constipation,Take according to package instructions and mai...,7.5 mg to 15 mg,24,Long-term or excessive use may cause bowel or ...,Medium
23,23.0,23.0,24,Telfast,Fexofenadine,Over-the-Counter (OTC),Hay fever and hives,Take according to the product instructions.,120 mg to 180 mg,24,Follow age restrictions and product instructions.,Low
24,24.0,24.0,25,Aerius,Desloratadine,Over-the-Counter (OTC),Hay fever and hives,Take once daily as directed.,5 mg,24,Seek medical advice if symptoms persist despit...,Low
25,25.0,25.0,26,Augmentin,"Amoxicillin, Clavulanic acid",Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Do not take if you have a serious penicillin a...,High
26,26.0,26.0,27,Cipro,Ciprofloxacin,Prescription,Certain bacterial infections,Take exactly as prescribed.,Product-dependent,12,Prescription medicine with important drug inte...,High
27,27.0,27.0,28,Flagyl,Metronidazole,Prescription,Certain bacterial and parasitic infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Prescription medicine. Follow medical advice r...,High
28,28.0,28.0,29,Vicks,"Menthol, Camphor",First Aid,Minor cold symptoms and nasal congestion,Use according to the specific product instruct...,Product-dependent,6,Do not ingest products intended only for exter...,Low
29,0.0,NaN,30,Voltaren,Diclofenac,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,25–50 mg,8,"Avoid if you have stomach ulcers, kidney probl...",Medium
0,NaN,NaN,31,Motrin,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,200–400 mg,6,Avoid combining with other NSAIDs,Medium

In [113]:
medicine.to_csv("../../excercises/week2/Medical_Tracker.csv")

### Search for medications by active ingredient/symptom

In [114]:
search = input("enter an ingredient or symptoms ")
print(search)

df = pd.read_csv('../../excercises/week2/Medical_Tracker.csv')

search = (df[df['symptoms'].str.contains(search)  | df['ingredient'].str.contains(search)])
search

Pain

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,name,ingredient,category,symptoms,instructions,dosage,frequency_hours,safety,urgency
1,1,1.0,1.0,2,Advil,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, swelling, menstrual cramps...",Take with food or milk if it causes stomach ir...,200 mg to 400 mg,6,Avoid or seek medical advice if you have stoma...,Medium
4,4,4.0,4.0,5,Calpol,Paracetamol,Over-the-Counter (OTC),Pain and fever,Follow the product instructions and use the ap...,500 mg to 1000 mg,4,Do not combine with other paracetamol-containi...,Low
5,5,5.0,5.0,6,Nurofen,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and fever",Take with water. Food may help reduce stomach ...,200 mg to 400 mg,6,"NSAID precautions apply, particularly with sto...",Medium
29,29,0.0,NaN,30,Voltaren,Diclofenac,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,25–50 mg,8,"Avoid if you have stomach ulcers, kidney probl...",Medium
30,0,NaN,NaN,31,Motrin,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,200–400 mg,6,Avoid combining with other NSAIDs,Medium

### View all logged medications

In [115]:
medicine[['name','dosage']]

             name                               dosage
0         Panadol                    500 mg to 1000 mg
1           Advil                     200 mg to 400 mg
2          Anadin                     325 mg to 650 mg
3          Amoxil                     250 mg to 500 mg
4          Calpol                    500 mg to 1000 mg
5         Nurofen                     200 mg to 400 mg
6         Tylenol                    500 mg to 1000 mg
7   Panadol Extra  500 mg Paracetamol + 65 mg Caffeine
8        Clarityn                                10 mg
9      Loratadine                                10 mg
10         Zyrtec                                10 mg
11     Cetirizine                                10 mg
12       Gaviscon                    Product-dependent
13         Nexium                                20 mg
14          Losec                                20 mg
15        Imodium                    Product-dependent
16       Buscopan                       10 mg to 20 mg
17        Sudafed                    Product-dependent
18       Benadryl                    Product-dependent
19      Strepsils                    Product-dependent
20       Canesten                    Product-dependent
21       Dulcolax                        5 mg to 10 mg
22        Senokot                      7.5 mg to 15 mg
23        Telfast                     120 mg to 180 mg
24         Aerius                                 5 mg
25      Augmentin                    Product-dependent
26          Cipro                    Product-dependent
27         Flagyl                    Product-dependent
28          Vicks                    Product-dependent
29       Voltaren                             25–50 mg
0          Motrin                           200–400 mg

### View a random wellness tip or medication spotlight from the database

In [116]:
import pandas as pd
df = pd.read_csv('../../excercises/week2/Medical_Tracker.csv')

random = df['safety'].sample()
random

29    Avoid if you have stomach ulcers, kidney probl...
Name: safety, dtype: str

In [117]:
medicine

,Unnamed: 0.1,Unnamed: 0,id,name,ingredient,category,symptoms,instructions,dosage,frequency_hours,safety,urgency
0,0.0,0.0,1,Panadol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Swallow tablets with water. Can be taken with ...,500 mg to 1000 mg,4,Do not combine with other products containing ...,Low
1,1.0,1.0,2,Advil,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, swelling, menstrual cramps...",Take with food or milk if it causes stomach ir...,200 mg to 400 mg,6,Avoid or seek medical advice if you have stoma...,Medium
2,2.0,2.0,3,Anadin,Aspirin,Over-the-Counter (OTC),Mild pain and fever,Swallow tablets as directed. Enteric-coated ta...,325 mg to 650 mg,4,Aspirin can increase bleeding risk and should ...,Medium
3,3.0,3.0,4,Amoxil,Amoxicillin,Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,250 mg to 500 mg,8,Do not take if you have a known serious penici...,High
4,4.0,4.0,5,Calpol,Paracetamol,Over-the-Counter (OTC),Pain and fever,Follow the product instructions and use the ap...,500 mg to 1000 mg,4,Do not combine with other paracetamol-containi...,Low
5,5.0,5.0,6,Nurofen,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and fever",Take with water. Food may help reduce stomach ...,200 mg to 400 mg,6,"NSAID precautions apply, particularly with sto...",Medium
6,6.0,6.0,7,Tylenol,Paracetamol,Over-the-Counter (OTC),Mild-to-moderate pain and fever,Take with water and follow the product instruc...,500 mg to 1000 mg,6,Do not combine with other products containing ...,Low
7,7.0,7.0,8,Panadol Extra,"Paracetamol, Caffeine",Over-the-Counter (OTC),"Headache, pain, and fever",Swallow tablets with water and follow the prod...,500 mg Paracetamol + 65 mg Caffeine,4,Avoid combining with other paracetamol-contain...,Medium
8,8.0,8.0,9,Clarityn,Loratadine,Over-the-Counter (OTC),"Hay fever, sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,Seek medical advice if allergy symptoms are se...,Low
9,9.0,9.0,10,Loratadine,Loratadine,Over-the-Counter (OTC),Allergy symptoms such as sneezing and itchy eyes,Take once daily as directed.,10 mg,24,Do not exceed the recommended dose.,Low
10,10.0,10.0,11,Zyrtec,Cetirizine,Over-the-Counter (OTC),"Sneezing, runny nose, and itchy eyes",Take once daily with or without food.,10 mg,24,May cause drowsiness in some people.,Low
11,11.0,11.0,12,Cetirizine,Cetirizine,Over-the-Counter (OTC),Allergy symptoms and hay fever,Take according to the product instructions.,10 mg,24,May cause drowsiness. Avoid driving if affected.,Low
12,12.0,12.0,13,Gaviscon,"Sodium alginate, Calcium carbonate",Over-the-Counter (OTC),"Heartburn, acid reflux, and indigestion","Take according to the product instructions, co...",Product-dependent,8,Seek medical advice for persistent or severe r...,Low
13,13.0,13.0,14,Nexium,Esomeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
14,14.0,14.0,15,Losec,Omeprazole,Prescription,Frequent heartburn and acid reflux,Usually taken before meals as directed by a he...,20 mg,24,Long-term use should generally be monitored by...,Medium
15,15.0,15.0,16,Imodium,Loperamide,Over-the-Counter (OTC),Short-term relief of uncomplicated diarrhea,Follow package directions and maintain adequat...,Product-dependent,6,Do not use for bloody diarrhea or high fever w...,Medium
16,16.0,16.0,17,Buscopan,Hyoscine butylbromide,Over-the-Counter (OTC),Abdominal cramps and spasms,Take as directed for abdominal cramps.,10 mg to 20 mg,6,Seek medical advice for severe or unexplained ...,Medium
17,17.0,17.0,18,Sudafed,Pseudoephedrine,Over-the-Counter (OTC),Nasal congestion from colds or allergies,Follow package directions and do not exceed th...,Product-dependent,6,May raise blood pressure or cause palpitations...,Medium
18,18.0,18.0,19,Benadryl,Diphenhydramine,Over-the-Counter (OTC),Allergy symptoms and some cold symptoms,Follow package instructions. May cause drowsin...,Product-dependent,6,May cause significant drowsiness. Avoid combin...,Medium
19,19.0,19.0,20,Strepsils,Amylmetacresol,Over-the-Counter (OTC),Sore throat and minor mouth irritation,Allow the lozenge to dissolve slowly in the mo...,Product-dependent,3,Do not exceed the recommended amount.,Low
20,20.0,20.0,21,Canesten,Clotrimazole,Over-the-Counter (OTC),Fungal skin infections such as athlete’s foot,Apply to the affected area as directed and kee...,Product-dependent,12,For external use only. Stop if severe irritati...,Low
21,21.0,21.0,22,Dulcolax,Bisacodyl,Over-the-Counter (OTC),Occasional constipation,Take with water and follow package instructions.,5 mg to 10 mg,24,Overuse can cause abdominal cramps and electro...,Medium
22,22.0,22.0,23,Senokot,Senna,Supplement,Occasional constipation,Take according to package instructions and mai...,7.5 mg to 15 mg,24,Long-term or excessive use may cause bowel or ...,Medium
23,23.0,23.0,24,Telfast,Fexofenadine,Over-the-Counter (OTC),Hay fever and hives,Take according to the product instructions.,120 mg to 180 mg,24,Follow age restrictions and product instructions.,Low
24,24.0,24.0,25,Aerius,Desloratadine,Over-the-Counter (OTC),Hay fever and hives,Take once daily as directed.,5 mg,24,Seek medical advice if symptoms persist despit...,Low
25,25.0,25.0,26,Augmentin,"Amoxicillin, Clavulanic acid",Prescription,Certain bacterial infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Do not take if you have a serious penicillin a...,High
26,26.0,26.0,27,Cipro,Ciprofloxacin,Prescription,Certain bacterial infections,Take exactly as prescribed.,Product-dependent,12,Prescription medicine with important drug inte...,High
27,27.0,27.0,28,Flagyl,Metronidazole,Prescription,Certain bacterial and parasitic infections,Take exactly as prescribed and complete the pr...,Product-dependent,8,Prescription medicine. Follow medical advice r...,High
28,28.0,28.0,29,Vicks,"Menthol, Camphor",First Aid,Minor cold symptoms and nasal congestion,Use according to the specific product instruct...,Product-dependent,6,Do not ingest products intended only for exter...,Low
29,0.0,NaN,30,Voltaren,Diclofenac,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,25–50 mg,8,"Avoid if you have stomach ulcers, kidney probl...",Medium
0,NaN,NaN,31,Motrin,Ibuprofen,Over-the-Counter (OTC),"Pain, inflammation, and swelling",Take with food or milk to reduce stomach irrit...,200–400 mg,6,Avoid combining with other NSAIDs,Medium

### users medicine(with exp and next pill)

In [6]:
my_tracker = pd.DataFrame({
    'name': [''],
    'ingredient': [''],
    'dosage': [''],
    'exp': [''],
    'next': ['']
})

In [12]:
my_tracker.to_csv("My_Medications.csv")

In [14]:
my_tracker = pd.read_csv("My_Medications.csv")
my_tracker

   Unnamed: 0.1  Unnamed: 0  medicine   ingredient   dosage  exp   next
0             0           0        NaN          NaN     NaN   NaN   NaN

In [47]:
medicine = pd.read_csv("Medical_Tracker.csv")

medicine_name = input("Which medicine do you want to add? ")

selected = medicine[medicine["name"] == medicine_name].loc[0]
print(selected)

Unnamed: 0.2                                                     0.0
Unnamed: 0.1                                                     0.0
Unnamed: 0                                                       0.0
id                                                                 1
name                                                         Panadol
ingredient                                               Paracetamol
category                                      Over-the-Counter (OTC)
symptoms                             Mild-to-moderate pain and fever
instructions       Swallow tablets with water. Can be taken with ...
dosage                                             500 mg to 1000 mg
frequency_hours                                                    4
safety             Do not combine with other products containing ...
urgency                                                          Low
Name: 0, dtype: object

In [48]:
name = selected["name"]
ing = selected["ingredient"]
dosage = selected["dosage"]
frequency = selected["frequency_hours"]

In [49]:
print(name)
print(ing)
print(dosage)
print(frequency)

Panadol
Paracetamol
500 mg to 1000 mg
4

In [50]:
exp = input("whats the expiry date")

taken_medicine = input("Have you taken the medicine")

if taken_medicine == "yes" or "Yes":
    now = datetime.now()
    next = now + timedelta(hours=int(frequency))

print("medicine taken!")
print(f"next dosage: {next}")

medicine taken!
next dosage: 2026-09-20 20:28:41.889110

In [51]:
print(exp)
print(f'the next dosage is after {next} hours')

20/02/2027
the next dosage is after 2026-09-20 20:28:41.889110 hours

In [53]:
client = [{"name": name, "ingredient":ing,"dosage": dosage, "expiry":exp, "next_dosage": next,
}]

In [54]:
df = pd.DataFrame(client)

In [58]:
df

,name,ingredient,dosage,expiry,next_dosage
0,Panadol,Paracetamol,500 mg to 1000 mg,20/02/2027,2026-09-20 20:28:41.889110

In [59]:
df.to_csv("../../excercises/week2/My_Medications.csv")